### ISSUE TITLE
Wrong order of exports in package.json

### ISSUE THREAD

**Issue by larslaade** [SirPepe/ornament#3]
I get the error "Module not found: Default condition should be last one" in my project.

Currently the order for exports is "types", "default", "require" but should be "types", "require", "default".

When I correct this in ornament in my local node_modules folder the error disappears.

**Comment by SirPepe** [comment]
I'm gonna fix that, but just out of curiosity: what's your setup? Because my setup(s) don't complain about that at all.

**Comment by larslaade** [comment]
I have just a small setup with webpack + ts-loader. In tsconfig I had to add "esnext.decorators" to "lib" to get decorators to work at all.

### package.json

`
{
  "version": "0.0.1",
  "private": true,
  "main": "dist/index.js",
  "type": "module",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "webpack serve --open",
    "build": "cross-env NODE_ENV=production webpack --mode=production --config webpack.config.js"
  },
  "dependencies": {
    "@sirpepe/ornament": "0.0.9",
    "uhtml": "3.2.2"
  },
  "devDependencies": {
    "autoprefixer": "10.4.16",
    "clean-webpack-plugin": "4.0.0",
    "cross-env": "7.0.3",
    "css-loader": "6.8.1",
    "postcss": "8.4.31",
    "postcss-loader": "7.3.3",
    "postcss-sort-media-queries": "5.2.0",
    "ts-loader": "9.5.0",
    "typescript": "5.2.2",
    "webpack": "5.88.2",
    "webpack-cli": "5.1.4",
    "webpack-dev-server": "4.15.1"
  },
  "browserslist": [
    "> .5% and last 2 versions",
    "not ie <= 11",
    "not op_mini all",
    "not dead"
  ]
}
`

### tsconfig

`
{
  "compilerOptions": {
    "target": "es2022",
    "module": "esnext",
    "lib": [
      "es2022",
      "esnext.decorators",
      "dom",
      "dom.iterable"
    ],
    "sourceMap": true,
    "outDir": "./dist",
    "removeComments": true,
    "noEmitOnError": true,
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "moduleResolution": "bundler"
  },
  "include": [
    "**/*"
  ],
  "exclude": [
    "node_modules",
    "dist"
  ]
}
`

**Comment by larslaade** [comment]
Now with ornament 0.0.11 I do not need "esnext.decorators" in "lib" anymore ¯\_(ツ)_/¯
